SELECTION-SCREEN BEGIN OF BLOCK bi.
    PARAMETER p_1bim(12) TYPE p DECIMALS 2.
    PARAMETER p_2bim(12) TYPE p DECIMALS 2.
    PARAMETER p_3bim(12) TYPE p DECIMALS 2.
    PARAMETER p_4bim(12) TYPE p DECIMALS 2.
SELECTION-SCREEN END OF BLOCK bi.
