MODULE pbo_9000 OUTPUT.
  SET TITLEBAR 'T9000' WITH '123456.'.
ENDMODULE.

MODULE pai_9000 INPUT.
  MESSAGE sy-ucomm TYPE 'S'.

  CASE sy-ucomm.
    WHEN 'BACK'.
    LEAVE TO SCREEN 0.
  ENDCASE.
 ENDMODULE.
