REPORT ZVARIANTE.

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-001.
    PARAMETERS p_pnome TYPE char35.
    PARAMETERS p_unome TYPE char35.
    PARAMETERS p_email TYPE char255.
SELECTION-SCREEN END OF BLOCK b1.


SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE text-002.
    PARAMETERS p_cep TYPE char10.
    PARAMETERS p_rua TYPE char35.
    PARAMETERS p_numero TYPE char10.
    PARAMETERS p_bairro TYPE char255.
    PARAMETERS p_cidade TYPE char255.
    PARAMETERS p_uf TYPE char2.
SELECTION-SCREEN END OF BLOCK b2.


SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE text-003.
    PARAMETERS p_ativo TYPE flag.
SELECTION-SCREEN END OF BLOCK b3.

START-OF-SELECTION.
    MESSAGE 'Programa executado' TYPE 'S'.
